{% set name = "ifcfg" %}
{% set version = "0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ftao/python-{{ name }}/archive/releases/{{ version }}.tar.gz
  sha256: 9b3baef6f21ace5741e3bedfc9208825dfd54480fa661148e0aeda1cfa16a6f5

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ifcfg

about:
  home: https://github.com/ftao/python-ifcfg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Ifconfig Wrapper for Unix/Linux/MacOSX

extra:
  recipe-maintainers:
    - seanyen
